name: Build and release

on: 
  push:
    tags:
      - '*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo $(go env GOPATH)/bin >> $GITHUB_PATH
    - name: Build Windows binary
      run: make windows
    - name: Build Linux binary
      run: make linux
    - name: Build Darwin binary
      run: make darwin
    - name: Upload Windows binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/androidqf_windows.exe
        asset_name: androidqf_windows.exe
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload Linux binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/androidqf_linux
        asset_name: androidqf_linux
        tag: ${{ github.ref }}
        overwrite: true        
    - name: Upload Darwin binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/androidqf_darwin
        asset_name: androidqf_darwin
        tag: ${{ github.ref }}
        overwrite: true        
